language: c

sudo: false

cache:
  directories:
    - $HOME/qemu
    - $HOME/toolchains

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang
  - os: linux
    env:
      LINARO_URL=https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/arm-linux-gnueabihf/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
      TARGET=arm-linux-gnueabihf
      QEMU_ARCHES=arm
      QEMU_ARCH=arm
  - os: linux
    env:
      LINARO_URL=https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/arm-linux-gnueabihf/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu.tar.xz
      TARGET=aarch64-linux-gnu
      QEMU_ARCHES=aarch64
      QEMU_ARCH=aarch64

script:
  - cmake --version
  - bash -e -x ./scripts/run_integration.sh
