language: c

sudo: false

cache:
  directories:
    - $HOME/qemu

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang
  - os: linux
    env:
      CROSS_COMPILE=1
      TOOLCHAIN_NAME=gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf
      TARGET=arm-linux-gnueabihf
      QEMU_ARCH=arm

script:
  - cmake --version
  - bash -e -x ./scripts/run_integration.sh
